name: Run Tests - SerenityJS Report

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  REPORT_DIR: "./target/site/serenity"

jobs:
  test:
    name: "ðŸ§ª Pruebas (Run Tests)"
    runs-on: ubuntu-latest
    environment: tokenADl   # <--- AquÃ­ se indica el environment
    steps:
      - name: ðŸ§© Checkout code
        uses: actions/checkout@v4

      - name: âš™ï¸ Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: ðŸ“¦ Install dependencies
        run: npm ci

      - name: â˜• Install Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: ðŸ§ª Run tests and generate Serenity JSON
        env:
          AT: ${{ secrets.AT }}                 
        run: |
          echo "El valor del secret AT es: $AT"          
          npx cucumber-js
          --require-module ts-node/register
          --require src/support/serenity.config.ts
          --require src/support/hooks.config.ts
          --require src/steps/**/*.ts
          src/features/**/*.feature
          --format @serenity-js/cucumber
          --format-options "{\"outputDirectory\": \"$REPORT_DIR\", \"specDirectory\": \"src/features\"}"
        continue-on-error: true

      - name: ðŸ“¤ Upload Serenity JSON artifact
        uses: actions/upload-artifact@v4
        with:
          name: serenity-json
          path: ${{ env.REPORT_DIR }}

  generate_report:
    name: "ðŸ“Š Reporte (Generate Report)"
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: ðŸ§© Checkout code
        uses: actions/checkout@v4

      - name: ðŸ“¥ Download Serenity JSON artifact
        uses: actions/download-artifact@v4
        with:
          name: serenity-json
          path: ${{ env.REPORT_DIR }}

      - name: âš™ï¸ Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: ðŸ“¦ Install dependencies
        run: npm ci

      - name: â˜• Install Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: ðŸ§® Generate Serenity BDD HTML report
        run: npx serenity-bdd run --destination $REPORT_DIR

      - name: ðŸ“¤ Upload Serenity report artifact
        uses: actions/upload-artifact@v4
        with:
          name: serenity-report
          path: ${{ env.REPORT_DIR }}

  deploy_report:
    name: "ðŸš€ Deploy (GitHub Pages)"
    runs-on: ubuntu-latest
    needs: generate_report
    steps:
      - name: ðŸ“¥ Download Serenity report artifact
        uses: actions/download-artifact@v4
        with:
          name: serenity-report
          path: ${{ env.REPORT_DIR }}

      - name: ðŸŒ Deploy Serenity Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ env.REPORT_DIR }}